# permissions for end users to view hanaexpresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hanaexpress-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sap-hana-express-operator
    app.kubernetes.io/part-of: sap-hana-express-operator
    app.kubernetes.io/managed-by: kustomize
  name: hanaexpress-viewer-role
rules:
- apiGroups:
  - db.sap-redhat.io
  resources:
  - hanaexpresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.sap-redhat.io
  resources:
  - hanaexpresses/status
  verbs:
  - get
