apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: sap-hana-express-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HanaExpress is the Schema for the hanaexpresses API
      displayName: Hana Express
      kind: HanaExpress
      name: hanaexpresses.db.sap-redhat.io
      statusDescriptors:
      - description: Conditions store the status conditions of the HanaExpress instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: Operator for managing the lifecycle of SAP Hana Express on Kubernetes
    platform
  displayName: SAP Hana Express Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Database
  links:
  - name: Sap Hana Express Operator
    url: https://sap-hana-express-operator.domain
  maturity: alpha
  provider:
    name: SAP LinuxLab - Red Hat
  version: 0.0.0
